### ISSUE TITLE
Glitch while removing items from the selection when searching for something

### ISSUE THREAD

**Issue by Arafatmollik1** [alexpechkarev/alpinejs-multiselect#3]
https://github.com/user-attachments/assets/e4fbb8d7-503a-4be2-9f08-3e47ba2b2d69

**Comment by Arafatmollik1** [comment]
@alexpechkarev

**Comment by alexpechkarev** [comment]
Thank you for picking this up @Arafatmollik1 ! The fix has been added.

**Comment by Arafatmollik1** [comment]
Thank you.
